import json

# ── 공통 유틸 ────────────────────────────────────────────────
def patch_cell(nb, idx, src):
    nb['cells'][idx]['source'] = src
    nb['cells'][idx]['outputs'] = []
    nb['cells'][idx]['execution_count'] = None

# ════════════════════════════════════════════════════════════
# 02_eda_analysis.ipynb
# ════════════════════════════════════════════════════════════
with open('notebooks/02_eda_analysis.ipynb') as f:
    nb02 = json.load(f)

# ── Cell 6: fig2_normalized_trends ──────────────────────────
cell6 = (
    "# ── 주요 이벤트 정의 ─────────────────────────────────────────\n"
    "EVENTS = [\n"
    "    {'date': '2020-03-19', 'label': 'COVID\\n저점',    'color': '#d62728'},\n"
    "    {'date': '2021-01-11', 'label': '삼성\\n최고가',    'color': '#1f77b4'},\n"
    "    {'date': '2022-03-16', 'label': '미연준\\n첫 금리인상', 'color': '#ff7f0e'},\n"
    "    {'date': '2023-01-06', 'label': '반도체\\n반등 시작', 'color': '#2ca02c'},\n"
    "    {'date': '2024-07-10', 'label': 'AI 반도체\\n호황',  'color': '#9467bd'},\n"
    "]\n"
    "\n"
    "def add_events(ax):\n"
    "    for ev in EVENTS:\n"
    "        ax.axvline(pd.Timestamp(ev['date']), color=ev['color'],\n"
    "                   linestyle='--', alpha=0.6, linewidth=1)\n"
    "        ylim = ax.get_ylim()\n"
    "        y_pos = ylim[0] + (ylim[1] - ylim[0]) * 0.97\n"
    "        ax.text(pd.Timestamp(ev['date']), y_pos, ev['label'],\n"
    "                fontsize=6, ha='center', va='top', color=ev['color'],\n"
    "                bbox=dict(boxstyle='round,pad=0.1', facecolor='white', alpha=0.5, edgecolor='none'))\n"
    "\n"
    "# 정규화: 각 컬럼별 첫 유효값(non-NaN) 기준\n"
    "first_valid = master.apply(lambda col: col.dropna().iloc[0])\n"
    "norm = master.div(first_valid) * 100\n"
    "\n"
    "fig, axes = plt.subplots(3, 1, figsize=(14, 12), sharex=True)\n"
    "fig.suptitle('주요 변수 정규화 추이 (각 시계열 첫 거래일 = 100)', fontsize=13, fontweight='bold')\n"
    "\n"
    "ax = axes[0]\n"
    "for col, style in [('samsung', '-'), ('skhynix', '--'), ('naver', ':'), ('kospi', '-')]:\n"
    "    norm[col].dropna().plot(ax=ax, label=col, linewidth=1.2, linestyle=style)\n"
    "ax.set_title('한국 주식 vs KOSPI', fontsize=10)\n"
    "ax.set_ylabel('정규화 지수')\n"
    "ax.legend(fontsize=8, loc='upper left')\n"
    "ax.axhline(100, color='gray', linestyle=':', alpha=0.4)\n"
    "add_events(ax)\n"
    "\n"
    "ax = axes[1]\n"
    "for col in ['sp500', 'nasdaq', 'kospi']:\n"
    "    norm[col].dropna().plot(ax=ax, label=col, linewidth=1.2)\n"
    "ax.set_title('글로벌 지수 비교', fontsize=10)\n"
    "ax.set_ylabel('정규화 지수')\n"
    "ax.legend(fontsize=8, loc='upper left')\n"
    "ax.axhline(100, color='gray', linestyle=':', alpha=0.4)\n"
    "add_events(ax)\n"
    "\n"
    "ax = axes[2]\n"
    "for col in ['usdkrw', 'wti', 'gold', 'us10y']:\n"
    "    norm[col].dropna().plot(ax=ax, label=col, linewidth=1.2)\n"
    "ax.set_title('외부 변수 (환율·유가·금·금리)', fontsize=10)\n"
    "ax.set_ylabel('정규화 지수')\n"
    "ax.legend(fontsize=8, loc='upper left')\n"
    "ax.axhline(100, color='gray', linestyle=':', alpha=0.4)\n"
    "add_events(ax)\n"
    "\n"
    "# xlim 명시 + DateFormatter만 설정 (MonthLocator 제거)\n"
    "date_min = master.apply(lambda c: c.dropna().index.min()).min()\n"
    "date_max = master.index.max()\n"
    "axes[-1].set_xlim(date_min, date_max)\n"
    "axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))\n"
    "plt.setp(axes[-1].xaxis.get_majorticklabels(), rotation=30, ha='right')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIG_DIR / 'fig2_normalized_trends.png', bbox_inches='tight')\n"
    "plt.show()\n"
)
patch_cell(nb02, 6, cell6)

# ── Cell 12: fig6_rolling_correlation ───────────────────────
cell12 = (
    "WINDOW = 60\n"
    "rolling_corr_vars = ['kospi', 'sp500', 'usdkrw', 'wti', 'us10y']\n"
    "\n"
    "rolling_corrs = pd.DataFrame({\n"
    "    var: returns['samsung'].rolling(WINDOW).corr(returns[var])\n"
    "    for var in rolling_corr_vars\n"
    "})\n"
    "\n"
    "valid_start = rolling_corrs.dropna(how='all').index.min()\n"
    "valid_end   = rolling_corrs.index.max()\n"
    "\n"
    "fig, axes = plt.subplots(len(rolling_corr_vars), 1, figsize=(14, 14), sharex=True)\n"
    "fig.suptitle(f'삼성전자와 외부 변수 간 롤링 상관계수 ({WINDOW}일)', fontsize=13, fontweight='bold')\n"
    "\n"
    "for ax, var in zip(axes, rolling_corr_vars):\n"
    "    r = rolling_corrs[var].dropna()\n"
    "    ax.plot(r.index, r, linewidth=1, color='steelblue')\n"
    "    ax.fill_between(r.index, r, 0, where=(r > 0), alpha=0.2, color='green', label='양의 상관')\n"
    "    ax.fill_between(r.index, r, 0, where=(r < 0), alpha=0.2, color='red',   label='음의 상관')\n"
    "    ax.axhline(0,    color='black', lw=0.8)\n"
    "    ax.axhline(0.5,  color='green', lw=0.5, linestyle='--', alpha=0.5)\n"
    "    ax.axhline(-0.5, color='red',   lw=0.5, linestyle='--', alpha=0.5)\n"
    "    ax.set_ylabel(f'r (samsung\\nvs {var})', fontsize=8)\n"
    "    ax.set_ylim(-1.1, 1.1)\n"
    "    ax.legend(fontsize=7, loc='upper right')\n"
    "    for ev in EVENTS:\n"
    "        ax.axvline(pd.Timestamp(ev['date']), color=ev['color'], linestyle='--', alpha=0.5, lw=0.8)\n"
    "\n"
    "# xlim 명시 + DateFormatter만 설정 (MonthLocator 제거)\n"
    "axes[-1].set_xlim(valid_start, valid_end)\n"
    "axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))\n"
    "plt.setp(axes[-1].xaxis.get_majorticklabels(), rotation=30, ha='right')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIG_DIR / 'fig6_rolling_correlation.png', bbox_inches='tight')\n"
    "plt.show()\n"
)
patch_cell(nb02, 12, cell12)

# ── Cell 18: fig9_volatility ─────────────────────────────────
cell18 = (
    "VOL_WINDOW = 20\n"
    "vol_assets = ['samsung', 'kospi', 'sp500', 'usdkrw']\n"
    "\n"
    "rolling_vol = returns[vol_assets].rolling(VOL_WINDOW).std() * np.sqrt(252) * 100\n"
    "\n"
    "fig, axes = plt.subplots(2, 1, figsize=(14, 9), sharex=True)\n"
    "fig.suptitle('롤링 변동성 분석 (20일, 연율화)', fontsize=13, fontweight='bold')\n"
    "\n"
    "ax = axes[0]\n"
    "for col in vol_assets:\n"
    "    rolling_vol[col].dropna().plot(ax=ax, label=col, lw=1.2)\n"
    "ax.set_ylabel('연율화 변동성 (%)')\n"
    "ax.set_title('주요 자산 변동성 추이')\n"
    "ax.legend(fontsize=8)\n"
    "ax.axhline(rolling_vol['samsung'].mean(), color='blue', linestyle='--', alpha=0.5, lw=0.8)\n"
    "for ev in EVENTS:\n"
    "    ax.axvline(pd.Timestamp(ev['date']), color=ev['color'], linestyle='--', alpha=0.4, lw=0.8)\n"
    "\n"
    "ax2  = axes[1]\n"
    "ax2b = ax2.twinx()\n"
    "samsung_clean = master['samsung'].dropna()\n"
    "vol_clean     = rolling_vol['samsung'].dropna()\n"
    "samsung_clean.plot(ax=ax2,  color='steelblue', lw=1,   label='삼성전자 종가', alpha=0.7)\n"
    "vol_clean.plot(    ax=ax2b, color='red',        lw=1,   label='변동성',       alpha=0.6)\n"
    "ax2.set_ylabel('종가 (KRW)', color='steelblue')\n"
    "ax2b.set_ylabel('연율화 변동성 (%)', color='red')\n"
    "ax2.set_title('삼성전자: 주가 vs 변동성')\n"
    "lines1, labels1 = ax2.get_legend_handles_labels()\n"
    "lines2, labels2 = ax2b.get_legend_handles_labels()\n"
    "ax2.legend(lines1 + lines2, labels1 + labels2, fontsize=8, loc='upper right')\n"
    "\n"
    "# xlim 명시 + DateFormatter만 설정 (MonthLocator 제거)\n"
    "axes[-1].set_xlim(samsung_clean.index.min(), samsung_clean.index.max())\n"
    "axes[-1].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))\n"
    "plt.setp(axes[-1].xaxis.get_majorticklabels(), rotation=30, ha='right')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(FIG_DIR / 'fig9_volatility.png', bbox_inches='tight')\n"
    "plt.show()\n"
)
patch_cell(nb02, 18, cell18)

with open('notebooks/02_eda_analysis.ipynb', 'w') as f:
    json.dump(nb02, f, indent=1)
print("02 저장 완료")

# ════════════════════════════════════════════════════════════
# 03_insights.ipynb
# ════════════════════════════════════════════════════════════
with open('notebooks/03_insights.ipynb') as f:
    nb03 = json.load(f)

# ── Cell 3: insight1_kospi_sync ──────────────────────────────
cell3 = (
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('인사이트 1: 삼성전자-KOSPI 동조화 추이', fontsize=13, fontweight='bold')\n"
    "\n"
    "ax = axes[0]\n"
    "years    = [int(y) for y in yearly_corr.index]\n"
    "kospi_r  = yearly_corr['kospi'].astype(float)\n"
    "sp500_r  = yearly_corr['sp500'].astype(float)\n"
    "nasdaq_r = yearly_corr['nasdaq'].astype(float)\n"
    "ax.plot(years, kospi_r,  'o-',  color='#1f77b4', lw=2,   label='vs KOSPI',  markersize=7)\n"
    "ax.plot(years, sp500_r,  's--', color='#ff7f0e', lw=1.5, label='vs S&P500', markersize=6)\n"
    "ax.plot(years, nasdaq_r, '^:',  color='#2ca02c', lw=1.5, label='vs NASDAQ', markersize=6)\n"
    "ax.fill_between(years, kospi_r, sp500_r, alpha=0.08, color='gray', label='KOSPI-SP500 격차')\n"
    "ax.axhline(0, color='black', lw=0.5)\n"
    "ax.set_ylim(-0.1, 1.0)\n"
    "ax.set_xticks(years)\n"
    "ax.set_ylabel('Pearson r')\n"
    "ax.set_title('연도별 상관계수 변화')\n"
    "ax.legend(fontsize=9)\n"
    "for yr, kr in zip(years, kospi_r):\n"
    "    ax.annotate(f'{kr:.2f}', (yr, kr), textcoords='offset points',\n"
    "                xytext=(0, 8), fontsize=8, ha='center', color='#1f77b4')\n"
    "\n"
    "ax = axes[1]\n"
    "rc_kospi = rolling_corr['kospi'].dropna()\n"
    "rc_sp500 = rolling_corr['sp500'].dropna()\n"
    "rc_kospi.plot(ax=ax, color='#1f77b4', lw=1.2, label='vs KOSPI')\n"
    "rc_sp500.plot(ax=ax, color='#ff7f0e', lw=1.2, label='vs S&P500', linestyle='--')\n"
    "ax.set_xlim(rc_kospi.index.min(), rc_kospi.index.max())\n"
    "ax.axhline(0, color='black', lw=0.5)\n"
    "ax.set_ylim(-0.5, 1.0)\n"
    "ax.set_title('60일 롤링 상관계수')\n"
    "ax.set_ylabel('Pearson r')\n"
    "ax.legend(fontsize=9)\n"
    "for d, lbl, c in [('2020-03-19', 'COVID', '#d62728'),\n"
    "                  ('2022-03-16', '금리인상', '#ff7f0e'),\n"
    "                  ('2023-01-06', '반도체반등', '#2ca02c')]:\n"
    "    ax.axvline(pd.Timestamp(d), color=c, linestyle='--', alpha=0.5, lw=0.9)\n"
    "    ax.text(pd.Timestamp(d), 0.95, lbl, fontsize=6, color=c, ha='center',\n"
    "            bbox=dict(facecolor='white', alpha=0.5, edgecolor='none', pad=0.5))\n"
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(PROCESSED_DIR / 'insight1_kospi_sync.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print('▶ 핵심 수치')\n"
    "print(f'  KOSPI 상관: 2020년 {kospi_r.iloc[0]:.2f} → 2024년 {kospi_r.iloc[-1]:.2f} (약화)')\n"
    "print(f'  S&P500 상관: 2020년 {sp500_r.iloc[0]:.2f} → 2024년 {sp500_r.iloc[-1]:.2f}')\n"
    "print()\n"
    "print('▶ 비즈니스 함의')\n"
    "print('  - KOSPI-삼성전자 상관이 2020->2024 완화: 반도체 업황 팩터 영향력 증가')\n"
    "print('  - S&P500 상관 낮음 -> 삼성전자는 미국 증시와의 분산 효과 존재')\n"
)
patch_cell(nb03, 3, cell3)

# ── Cell 5: insight2_usdkrw ──────────────────────────────────
cell5 = (
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('인사이트 2: 환율(USD/KRW)과 삼성전자 주가 관계', fontsize=13, fontweight='bold')\n"
    "\n"
    "ax  = axes[0]\n"
    "ax2 = ax.twinx()\n"
    "samsung_clean = master['samsung'].dropna()\n"
    "usdkrw_clean  = master['usdkrw'].dropna()\n"
    "samsung_clean.plot(ax=ax,  color='steelblue', lw=1.2, label='삼성전자 종가')\n"
    "usdkrw_clean.plot( ax=ax2, color='firebrick',  lw=1.2, label='USD/KRW', alpha=0.8)\n"
    "ax.set_xlim(samsung_clean.index.min(), samsung_clean.index.max())\n"
    "ax.set_ylabel('삼성전자 (KRW)', color='steelblue')\n"
    "ax2.set_ylabel('USD/KRW', color='firebrick')\n"
    "ax.set_title('삼성전자 종가 vs 환율')\n"
    "ax.tick_params(axis='y', labelcolor='steelblue')\n"
    "ax2.tick_params(axis='y', labelcolor='firebrick')\n"
    "lines1, labels1 = ax.get_legend_handles_labels()\n"
    "lines2, labels2 = ax2.get_legend_handles_labels()\n"
    "ax.legend(lines1 + lines2, labels1 + labels2, fontsize=8, loc='upper left')\n"
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))\n"
    "\n"
    "ax = axes[1]\n"
    "combined = pd.concat([returns['samsung'], returns['usdkrw']], axis=1).dropna()\n"
    "combined.columns = ['samsung_ret', 'usdkrw_ret']\n"
    "combined['usd_quartile'] = pd.qcut(\n"
    "    combined['usdkrw_ret'], q=4,\n"
    "    labels=['원화강세\\n(Q1)', '약간강세\\n(Q2)', '약간약세\\n(Q3)', '원화약세\\n(Q4)']\n"
    ")\n"
    "group_means = combined.groupby('usd_quartile', observed=True)['samsung_ret'].mean() * 100\n"
    "combined.boxplot(column='samsung_ret', by='usd_quartile', ax=ax,\n"
    "                 flierprops=dict(marker='.', markersize=2, alpha=0.3),\n"
    "                 boxprops=dict(color='steelblue'),\n"
    "                 medianprops=dict(color='red', lw=2),\n"
    "                 showfliers=False)\n"
    "ax.set_title('환율 변동 구간별 삼성전자 일간 수익률')\n"
    "ax.set_xlabel('USD/KRW 일간 변동 구간')\n"
    "ax.set_ylabel('삼성전자 일간 수익률')\n"
    "ax.axhline(0, color='black', lw=0.8, linestyle='--')\n"
    "plt.suptitle('')\n"
    "for i, (q, mean_val) in enumerate(group_means.items()):\n"
    "    ax.text(i + 1, ax.get_ylim()[1] * 0.85,\n"
    "            f'평균\\n{mean_val:+.3f}%', ha='center', fontsize=8,\n"
    "            color='#d62728' if mean_val < 0 else '#2ca02c', fontweight='bold')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(PROCESSED_DIR / 'insight2_usdkrw.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "q1_ret = combined[combined['usd_quartile'] == '원화강세\\n(Q1)']['samsung_ret']\n"
    "q4_ret = combined[combined['usd_quartile'] == '원화약세\\n(Q4)']['samsung_ret']\n"
    "t_stat, p_val = stats.ttest_ind(q1_ret, q4_ret)\n"
    "print(f'  t-검정: t={t_stat:.2f}, p={p_val:.4f}')\n"
)
patch_cell(nb03, 5, cell5)

# ── Cell 9: insight4_samsung_vs_skhynix ─────────────────────
cell9 = (
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('인사이트 4: 삼성전자 vs SK하이닉스', fontsize=13, fontweight='bold')\n"
    "\n"
    "ax = axes[0]\n"
    "cols = ['samsung', 'skhynix', 'kospi']\n"
    "# 각 컬럼 첫 유효값 기준 정규화 (iloc[0] NaN 방지)\n"
    "first_valid = master[cols].apply(lambda col: col.dropna().iloc[0])\n"
    "norm = master[cols].div(first_valid) * 100\n"
    "\n"
    "sam_s = norm['samsung'].dropna()\n"
    "sky_s = norm['skhynix'].dropna()\n"
    "ksp_s = norm['kospi'].dropna()\n"
    "common = sam_s.index.intersection(sky_s.index).intersection(ksp_s.index)\n"
    "\n"
    "sam_s.plot(ax=ax, color='#1f77b4', lw=2,   label='삼성전자')\n"
    "sky_s.plot(ax=ax, color='#d62728', lw=2,   label='SK하이닉스')\n"
    "ksp_s.plot(ax=ax, color='gray',    lw=1.5, label='KOSPI', linestyle='--', alpha=0.7)\n"
    "ax.axhline(100, color='black', lw=0.5, linestyle=':')\n"
    "\n"
    "sam_c = norm['samsung'].reindex(common)\n"
    "sky_c = norm['skhynix'].reindex(common)\n"
    "ax.fill_between(common, sky_c, sam_c,\n"
    "                where=(sky_c > sam_c),  alpha=0.1, color='red',  label='SK하이닉스 우위')\n"
    "ax.fill_between(common, sky_c, sam_c,\n"
    "                where=(sky_c <= sam_c), alpha=0.1, color='blue', label='삼성전자 우위')\n"
    "\n"
    "ax.set_xlim(common.min(), common.max())\n"
    "ax.set_ylabel('정규화 지수 (첫 거래일=100)')\n"
    "ax.set_title('5년 누적 성과 비교')\n"
    "ax.legend(fontsize=8)\n"
    "ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))\n"
    "\n"
    "ax = axes[1]\n"
    "years = [2020, 2021, 2022, 2023, 2024]\n"
    "sam_ann, sky_ann, ksp_ann = [], [], []\n"
    "for yr in years:\n"
    "    r = returns[returns.index.year == yr]\n"
    "    sam_ann.append(((1 + r['samsung']).prod() - 1) * 100)\n"
    "    sky_ann.append(((1 + r['skhynix']).prod() - 1) * 100)\n"
    "    ksp_ann.append(((1 + r['kospi']).prod()   - 1) * 100)\n"
    "x, w = np.arange(len(years)), 0.28\n"
    "bars1 = ax.bar(x - w, sam_ann, w, label='삼성전자',  color='#1f77b4', alpha=0.85)\n"
    "bars2 = ax.bar(x,     sky_ann, w, label='SK하이닉스', color='#d62728', alpha=0.85)\n"
    "bars3 = ax.bar(x + w, ksp_ann, w, label='KOSPI',     color='gray',    alpha=0.6)\n"
    "ax.axhline(0, color='black', lw=0.8)\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(years)\n"
    "ax.set_ylabel('연간 수익률 (%)')\n"
    "ax.set_title('연도별 수익률 비교')\n"
    "ax.legend(fontsize=8)\n"
    "for bars in [bars1, bars2, bars3]:\n"
    "    for bar in bars:\n"
    "        h = bar.get_height()\n"
    "        ax.text(bar.get_x() + bar.get_width()/2, h + (1 if h >= 0 else -3),\n"
    "                f'{h:.0f}%', ha='center', va='bottom', fontsize=6.5)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig(PROCESSED_DIR / 'insight4_samsung_vs_skhynix.png', bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print('▶ 5년 누적 수익률 (2020~2024)')\n"
    "for label, col in [('삼성전자', 'samsung'), ('SK하이닉스', 'skhynix'), ('KOSPI', 'kospi')]:\n"
    "    total = ((1 + returns[col]).prod() - 1) * 100\n"
    "    print(f'  {label}: {total:+.1f}%')\n"
)
patch_cell(nb03, 9, cell9)

with open('notebooks/03_insights.ipynb', 'w') as f:
    json.dump(nb03, f, indent=1)
print("03 저장 완료")
